<a href="https://colab.research.google.com/github/MunazaAshraf/Deep-Learning-BWF/blob/main/Task10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Create a NumPy ndarray Object

In [ ]:
v= np.array([1, 2, 3, 4, 5])
print(v)
print(type(v))

[1 2 3 4 5]
<class 'numpy.ndarray'>


To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

In [ ]:
arr = np.array((1, 2, 3, 4, 5))
print(arr)

[1 2 3 4 5]


Dimensions in Arrays

In [ ]:
# 0-D Arrays
arr = np.array(42)
print(arr)

42


In [ ]:
# 1-D Arrays
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [ ]:
# 2-D Arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 3-D Arrays
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


Check how many dimensions the arrays have

In [ ]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


Create an array with 5 dimensions and verify that it has 5 dimensions

In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[0])

[1 2 3 4]


In [ ]:
a = np.array([1, 2, 3, 4])
print(a[0])

1


In [ ]:
a = np.zeros(2)
print(a)

[0. 0.]


In [ ]:
a = np.zeros(7)
print(a)

[0. 0. 0. 0. 0. 0. 0.]


In [ ]:
a = np.ones(4)
print(a)

[1. 1. 1. 1.]


In [ ]:
a = np.empty(4)
print(a)

[1. 1. 1. 1.]


In [ ]:
a = np.empty(2)
print(a)

[0. 0.]
[0. 0.]


In [ ]:
a = np.linspace(0, 10, num=5)
print(a)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
a = np.ones(2, dtype=np.int64)
print(a)

[1 1]


In [ ]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.argsort(arr)

array([1, 0, 3, 5, 2, 6, 4, 7])

In [ ]:
np.lexsort(arr)

0

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [ ]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [ ]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [ ]:
array_example.ndim

3

In [ ]:
array_example.size

24

In [ ]:
array_example.shape

(3, 2, 4)

In [ ]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [ ]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [ ]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [ ]:
x = np.arange(10)
print(x)

One-dimensional subarrays

In [49]:
print(x[:5])

[0 1 2 3 4]


In [50]:
print(x[5:])

[5 6 7 8 9]


In [51]:
print(x[4:7])

[4 5 6]


In [52]:
print(x[::2])

[0 2 4 6 8]


In [53]:
print(x[1::2])

[1 3 5 7 9]


Multi-dimensional subarrays

In [54]:
x2 = np.array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [55]:
print(x2[:2, :3])

[[12  5  2]
 [ 7  6  8]]


In [56]:
print(x2[:3, ::2] )

[[12  2]
 [ 7  8]
 [ 1  7]]


In [57]:
x = np.array([[[1],[2]],[[3],[4]]])
print(x.shape)

(2, 2, 1)


In [64]:
a = np.random.randn(2,3)
b = np.random.randn(2,1)
c = a + b
print(c.shape)

(2, 3)


In [65]:
print(c)

[[ 1.63452442  0.21855455  1.8239102 ]
 [-0.82812516 -0.02712539 -0.92348651]]


In [66]:
a = np.random.randn(12288,150)
b = np.random.randn(150,45)
c = np.dot(a,b)

In [67]:
print(c)

[[  4.62333647   6.16947085  21.71352397 ...  23.44208682   1.49001881
   10.85955907]
 [-15.04572341 -11.20319983 -17.97977948 ...  12.36985248  12.53864282
   -9.49599624]
 [ 12.53900366   7.49419602  10.41880974 ...   0.60953032  -5.7769477
    0.81663635]
 ...
 [ 23.60276625 -23.34634171 -11.6036156  ...  20.08871567  21.44431101
  -16.3404164 ]
 [ -8.19844656  27.23856774   5.4019486  ... -15.05531218   6.68384714
   15.74493806]
 [  5.67190301 -12.07384422  22.99395014 ...   0.51800255   1.27598285
   17.94570473]]


In [68]:
print(c.shape)

(12288, 45)


In [69]:
a = np.random.randn(1,3)
b = np.random.randn(3,3)
c = a*b

In [70]:
print(c)
print(c.shape)

[[ 0.09944102 -0.56283045  0.82017186]
 [-0.11159689  1.12425341  0.54786585]
 [ 0.063136    0.58298175  0.53112756]]
(3, 3)


In [72]:
a = np.array([[2,1],[1,3]])
np.dot(a,a)

array([[ 5,  5],
       [ 5, 10]])

In [73]:
a = np.array([[1,1],[1,-1]])
b = np.array([[2],[3]])
c = a+b

In [74]:
print(c)

[[3 3]
 [4 2]]


In [77]:
a = np.arange(9, dtype = np.float_).reshape(3,3) 

print("First Array: ")
print(a)
print("\n")

First Array: 
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]




In [78]:
print("Second array:") 
b = np.array([10,10,10]) 
print(b) 
print("\n")  

Second array:
[10 10 10]




In [79]:
print("Add the two arrays:")
print( np.add(a,b)) 
print(" \n ")

print("Subtract the two arrays:")
print( np.subtract(a,b) )
print("\n")

print("Multiply the two arrays:") 
print( np.multiply(a,b) )
print("\n") 

print("Divide the two arrays: ")
print(np.divide(a,b))

Add the two arrays:
[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]
 
 
Subtract the two arrays:
[[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]


Multiply the two arrays:
[[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]


Divide the two arrays: 
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]
