<a href="https://colab.research.google.com/github/MunazaAshraf/Deep-Learning-BWF/blob/main/Task12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Broadcasting**

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python

In [2]:
import numpy as np

In [3]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])

**General Broadcasting Rules**

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimension and works its way left. Two dimensions are compatible when

--> they are equal, or

--> one of them is 1.

If these conditions are not met, a ValueError: operands could not be broadcast together exception is thrown, indicating that the arrays have incompatible shapes.

In [4]:
a = np.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])
b = np.array([1.0, 2.0, 3.0])
a + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [5]:
b = np.array([1.0, 2.0, 3.0, 4.0])
a + b

ValueError: ignored

In [6]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
a[:, np.newaxis] + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [7]:
observation = np.array([111.0, 188.0])
codes = np.array([[102.0, 203.0],
               [132.0, 193.0],
               [45.0, 155.0],
               [57.0, 173.0]])

In [10]:
diff = codes - observation    # the broadcast happens here
dist = np.sqrt(sum(diff**2))

In [11]:
dist

array([88.28363382, 39.54743987])

In [12]:
np.argmin(dist)

1

Observation      (2d array):      10 x 3

Codes            (3d array):   5 x 1 x 3

Diff             (3d array):  5 x 10 x 3

In [14]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  

In [15]:
a.shape

(4, 3)

In [16]:
b.shape

(3,)

In [17]:
a+b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [18]:
(a+b).shape

(4, 3)

In [19]:
a*b

array([[ 0.,  0.,  0.],
       [10., 20., 30.],
       [20., 40., 60.],
       [30., 60., 90.]])

In [20]:
(a*b).shape

(4, 3)

In [21]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 

In [22]:
b = np.array([[0.0,0.0],[10.0,10.0],[20.0,20.0],[30.0,30.0]]) 

In [24]:
a.shape

(4, 3)

In [25]:
b.shape

(4, 2)

In [26]:
(a+b).shape

ValueError: ignored